### PR TITLE
links all fixed closes #187

### LINKED ISSUE #187: Fix bad link on "No I am not registered" page
Can I Vote? -> No, I am not registered -> Step 2 "Register to vote here." image is linking to the wrong place.

It should link to https://www.ncsbe.gov/Voters/Registering-to-Vote or https://www.ncvoter.org/registering-to-vote/#three
Screen Shot 2020-08-26 at 7 38 03 PM

### PR DESCRIPTION
**Pull request by zenlex**
On "No I am not registered"  Page (VoterRequirements.jsx) I updated the links attached to the two large 'vote now' images to point to the NC board of Elections page. I also updated the urls for the other links on the page that were all pulling 404s due to updates at the NCBOE. The voter registration form link now points to the online registration portal that NC has implemented.

### CODE REVIEW

File: client/src/components/VoterRequirements.jsx [hunk 1]
```diff
@@ -1,69 +1,175 @@
...
+      you do not need the card in order to vote.
+    </p>
+    <h3 className="VoterRequirements-heading">
+      Military & Overseas Citizens Voting Information
+    </h3>
+    <p>
+      Some citizens, such as people serving in the military who are away from
+      their permanent home on Election Day, their families, or U.S. citizens who
+      are living abroad, have special voting rights and ways to register to
+      vote.{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:160]: Same comment about `{" "}`

File: client/src/components/VoterRequirements.jsx [hunk 2]
```diff
@@ -1,69 +1,175 @@
...
+    </p>
+    <p>
+      Once you have completed and mailed your changes to your local board of
+      elections, allow two to six weeks for delivery of your voter
+      identification card. Read the information thoroughly and note any changes
+      or mistakes on the card. A voter identification card is for your use only,
+      you do not need the card in order to vote.
+    </p>
+    <h3 className="VoterRequirements-heading">
+      Military & Overseas Citizens Voting Information
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:154]: Prefer to use HTML escaped ampersand (`&amp;`) over the regular old ampersand (`&`).  Or just spell out "and" to avoid the issue altogether.

I might be wrong altogether since this is a `.jsx` file, FWIW.

File: client/src/components/VoterRequirements.jsx [hunk 3]
```diff
@@ -1,69 +1,175 @@
...
+      register and/or vote through special programs for military and overseas
+      voters as described here.
+    </p>
+    <h3>
+      <a href="https://ncvoter.org/registering-to-vote/">
+        For more information visit this page from Democracy NC
+      </a>
+    </h3>
   </div>
 );
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:175]: I love the move to staying within 80 cols, it is so much more readable in the PR.  +1

File: client/src/components/VoterRequirements.jsx [hunk 4]
```diff
@@ -1,69 +1,175 @@
...
+      If you haven’t voted before, or haven’t voted in North Carolina, one of
+      your first questions is probably “Can I Vote?” We can help you answer
+      that!
+    </p>
+    <h2 className="VoterRequirements-heading">
+      Step 1: Review Qualifications to Vote
+    </h2>
+    <p>
+      To register to vote in North Carolina, a prospective voter must meet all
+      of the following qualifications:{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:28]: Why does this paragraph end in `{" "}`? This looks like a mistake that should be removed, but maybe I'm wrong and it's some react syntax.

File: client/src/components/VoterRequirements.jsx [hunk 5]
```diff
@@ -1,69 +1,175 @@
...
-    <p>Once you have completed and mailed your changes to your local board of elections, allow two to six weeks for delivery of your voter identification card. Read the information thoroughly and note any changes or mistakes on the card. A voter identification card is for your use only, you do not need the card in order to vote.</p>
-    <h3 className="VoterRequirements-heading">Military & Overseas Citizens Voting Information</h3>
-    <p>Some citizens, such as people serving in the military who are away from their permanent home on Election Day, their families, or U.S. citizens who are living abroad, have special voting rights and ways to register to vote. </p>
-    <p>If this describes you, you have the choice of either requesting a mail-in absentee ballot the same way as other registered voters, or applying to register and/or vote through special programs for military and overseas voters as described here.</p>
-    <h3><a href="https://ncvoter.org/registering-to-vote/">For more information visit this page from Democracy NC</a></h3>
+    <p>
+      If you’re not a first-time voter, you may have different questions -
+      hopefully we can help!{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:134]: Same comment about `{" "}`

File: client/src/components/VoterRequirements.jsx [hunk 6]
```diff
@@ -1,69 +1,175 @@
...
-        <li>You CAN submit this form without this; in that case you will be asked to show ID when you vote.</li>
+        <li>
+          You CAN submit this form without this; in that case you will be asked
+          to show ID when you vote.
+        </li>
       </ul>
-      <li>The mailing address of your county’s Board of Elections. Look that up on your favorite search engine or check the NC Board of Elections website <a href="https://vt.ncsbe.gov/BOEInfo">here</a>!</li>
+      <li>
+        The mailing address of your county’s Board of Elections. Look that up on
+        your favorite search engine or check the NC Board of Elections website{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:110]: Same comment about `{" "}`

File: client/src/components/VoterRequirements.jsx [hunk 7]
```diff
@@ -1,69 +1,175 @@
...
         width="250"
         alt="Register to vote here. 1"
         src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Register_to_vote_here._1.png/512px-Register_to_vote_here._1.png"
       />
     </a>
-    <p className="text-large" >If you meet the qualifications, your next step is registering to vote. In order to do this, you will need to complete and submit a voter registration form, which you can access <a href="https://www.ncsbe.gov/Voter-Information/VR-Form">here</a>. You will need the following information:</p>
+    <p className="text-large">
+      If you meet the qualifications, your next step is registering to vote. In
+      order to do this, you will need to complete and submit a voter
+      registration form, which you can access{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:73]: Same comment about `{" "}`

File: client/src/components/VoterRequirements.jsx [hunk 8]
```diff
@@ -1,69 +1,175 @@
...
+      </li>
+      <li>
+        Must be at least 18 years old. A prospective voter can submit a
+        registration form up to two years before his/her 18th birthday, if and
+        only if he/she will be 18 at the time of the next general election.
+      </li>
+      <li>
+        Must not be serving a sentence for a felony conviction (including
+        probation or parole). If a prospective voter has previously been
+        convicted of a felony, his/her citizenship rights must be restored.{" "}
```
Comment (tcaddy) [inline client/src/components/VoterRequirements.jsx:44]: Same comment about `{" "}`

File: client/src/components/VoterRequirements.jsx (hunk 1 above)
Comment (zenlex) [reply client/src/components/VoterRequirements.jsx:160]: The {" "} is one of two methods for adding space between elements in html inside a react JSX file - it strips out white space when it renders the HTML in places where you have other elements like embedded anchor tags. They were added by the linter, not coded in by hand. (&nbsp; is the other and there's issues with using HTML entities in JSX as well so the first approach is generally preferred at least as I understand it)

File: client/src/components/VoterRequirements.jsx (hunk 4 above)
Comment (zenlex) [reply client/src/components/VoterRequirements.jsx:28]: As i mentioned in another response, those were added by the linter in places where there was trailing or leading whitespace in an element as react strips that out. In this case because it was back to back <p> elements, it's not needed so I removed it and the whitespace that caused it. Usually I've only had to use that for spacing around mid-string anchor tags. I didn't write the original copy so there must have been some leading/trailing spaces in the paragraphs. I think I got them all that weren't needed.

**Comment by zenlex** [comment]
Did a squash and merge via GitHub rather than resubmit.
